name: PR Preview

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Patch homepage for PR preview
        run: |
          node -e "
            const fs = require('fs');
            const pkg = JSON.parse(fs.readFileSync('package.json'));
            pkg.homepage = 'https://petrilahdelma.github.io/randomgorsey/gh-pages-pr-${{ github.event.pull_request.number }}';
            fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Generate sitemap.xml and llms.txt
        run: npm run generate-meta

      - name: Build the React app
        run: npm run build

      - name: Remove CNAME (if exists)
        run: rm -f build/CNAME

      - name: Deploy to GitHub Pages (PR preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages-pr-${{ github.event.pull_request.number }}

      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;

            // ✅ Hardcode the correct GitHub Pages domain
            const previewUrl = `https://petrilahdelma.github.io/randomgorsey/gh-pages-pr-${prNumber}/`;
            const prUrl = `https://github.com/petrilahdelma/randomgorsey/pull/${prNumber}`;

            const message = `🚀 **PR Preview Available!**\n\n🔗 [Live Preview](${previewUrl})\n📄 [View PR](${prUrl})`;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
