name: PR Preview

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages (PR preview)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages-pr-${{ github.event.pull_request.number }}

      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const repoName = context.repo.repo;
            const owner = context.repo.owner;

            const previewUrl = `https://${owner}.github.io/${repoName}/gh-pages-pr-${prNumber}/`;
            const prUrl = `https://github.com/${owner}/${repoName}/pull/${prNumber}`;

            const body = `🚀 **PR Preview Available!**\n\n🔗 [Live Preview](${previewUrl})\n📄 [PR Page](${prUrl})`;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner,
              repo: repoName,
              body,
            });
